# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - main

jobs:
  # Building project
  build:
      name: Build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup Node
          uses: actions/setup-node@v3
        
        - name: Install dependencies
          uses: bahmutov/npm-install@v1

        - name: Build project
          run: npm run build
          env:
            VITE_EXCHANGE_VERSION: ${{ secrets.VITE_EXCHANGE_VERSION }}
            VITE_EXCHANGE_DATE: ${{ secrets.VITE_EXCHANGE_DATE }}

        - name: Upload production-ready build files
          uses: actions/upload-artifact@v3
          with:
              name: production-files
              path: ./dist

  # Deploying project
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
            name: production-files
            path: ./dist

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
